AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - spec/fixtures/**/*.rb

Style/StringLiterals:
  Enabled: false 

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Layout/EmptyLineBetweenDefs:
  Exclude:
    - lib/code_keeper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/HeredocIndentation:
  Exclude:
    - spec/code_keeper/formatter_spec.rb
    - lib/code_keeper/formatter.rb

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/code_keeper/formatter.rb # because uses here doc

# Because TargetFileNotFoundError needs to be passed an argument to initializer.
Style/RaiseArgs:
  Enabled: false 
