AllCops:
  Exclude:
    - spec/fixtures/**/*.rb

Style/StringLiterals:
  Enabled: false 

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Layout/EmptyLineBetweenDefs:
  Exclude:
    - lib/code_keeper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/HeredocIndentation:
  Exclude:
    - spec/code_keeper/formatter_spec.rb
    - lib/code_keeper/formatter.rb

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/code_keeper/formatter.rb # because uses here doc

# Because TargetFileNotFoundError needs to be passed an argument to initializer.
Style/RaiseArgs:
  Enabled: false 

Style/Documentation:
  Exclude:
    - lib/code_keeper.rb # Does not need documentation.

Metrics/AbcSize:
  Max: 25
  Exclude:
    # It's hard to control.
    - lib/code_keeper/metrics/class_length.rb

Metrics/CyclomaticComplexity:
  Exclude:
    # It's hard to control.
    - lib/code_keeper/metrics/class_length.rb 

Metrics/PerceivedComplexity:
  Exclude:
    # It's hard to control.
    - lib/code_keeper/metrics/class_length.rb 

Metrics/MethodLength:
  Max: 40
