AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - spec/fixtures/**/*.rb

Style/StringLiterals:
  Enabled: false 

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Layout/EmptyLineBetweenDefs:
  Exclude:
    - lib/code_keeper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
