AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - spec/fixtures/**/*.rb

Style/StringLiterals:
  Enabled: false 

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Layout/EmptyLineBetweenDefs:
  Exclude:
    - lib/code_keeper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout\HeredocIndentation:
  Exclude:
    - spec/code_keeper/formatter_spec.rb
    - lib/code_keeper/formatter.rb

Metrics/MethodLength:
  Exclude:
    - lib/code_keeper/formatter.rb # because uses here doc
